[advisories]
ignore = [
    # paste is unmaintained but not vulnerable - transitive dep from ksni and iced/rav1e
    # Tracked upstream, no action we can take until dependencies update
    "RUSTSEC-2024-0436",
]
